version: "3"
services:

    # app
    video-share:
        image: elyspio/video-share:latest
        container_name: video-share
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=external"
            - "traefik.http.middlewares.video-share-prefix.stripprefix.prefixes=/videos"
            - "traefik.http.routers.video-share.middlewares=video-share-prefix@docker"
            - "traefik.http.routers.video-share.rule=PathPrefix(`/videos`)"
            - "traefik.http.services.video-share.loadbalancer.server.port=4000"
            - "traefik.http.routers.video-share.entrypoints=external"
        volumes:
            - "./config/front/conf.js:/back/wwwroot/conf.js"
            - "./config/back/appsettings.json:/back/appsettings.json"
        environment:
            FILESERVE_USERNAME: ${AUTH_USERNAME}
            FILESERVE_PASSWORD: ${AUTH_PASSWORD}
            AUTHENTICATION_SERVER_URI: "https://elyspio.fr/authentication/"
            FFMPEG_PATH: ffmpeg
            FFPROBE_PATH: ffprobe
        networks:
            - video-share
            - external
        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            count: 1
                            capabilities: [ gpu ]
        devices:
            - /dev/nvidia0:/dev/nvidia0
            - /dev/nvidiactl:/dev/nvidiactl
            - /dev/nvidia-modeset:/dev/nvidia-modeset
            - /dev/nvidia-uvm:/dev/nvidia-uvm
            - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools

    video-share-db:
        container_name: video-share-db
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./data:/data/db
        networks:
            - video-share
        ports:
            - "27018:27017"



networks:
    video-share:
        name: "video-share"
    external:
        external: true

